//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiacEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class CheatCodes : global::System.Configuration.ApplicationSettingsBase {
        
        private static CheatCodes defaultInstance = ((CheatCodes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CheatCodes())));
        
        public static CheatCodes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideHUD {
            get {
                return ((bool)(this["HideHUD"]));
            }
            set {
                this["HideHUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreezeTimer {
            get {
                return ((bool)(this["FreezeTimer"]));
            }
            set {
                this["FreezeTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableBackgroundPausing {
            get {
                return ((bool)(this["DisableBackgroundPausing"]));
            }
            set {
                this["DisableBackgroundPausing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugMode {
            get {
                return ((bool)(this["EnableDebugMode"]));
            }
            set {
                this["EnableDebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableInstaSheildandDropDash {
            get {
                return ((bool)(this["EnableInstaSheildandDropDash"]));
            }
            set {
                this["EnableInstaSheildandDropDash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSuperPeelOut {
            get {
                return ((bool)(this["EnableSuperPeelOut"]));
            }
            set {
                this["EnableSuperPeelOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableSuperPeelOutAnimation {
            get {
                return ((bool)(this["DisableSuperPeelOutAnimation"]));
            }
            set {
                this["DisableSuperPeelOutAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableSuperMusic {
            get {
                return ((bool)(this["DisableSuperMusic"]));
            }
            set {
                this["DisableSuperMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSuperWithNoEmerlads {
            get {
                return ((bool)(this["EnableSuperWithNoEmerlads"]));
            }
            set {
                this["EnableSuperWithNoEmerlads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuperFormsCanBeCancelled {
            get {
                return ((bool)(this["SuperFormsCanBeCancelled"]));
            }
            set {
                this["SuperFormsCanBeCancelled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfiniteLives {
            get {
                return ((bool)(this["InfiniteLives"]));
            }
            set {
                this["InfiniteLives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfiniteRings {
            get {
                return ((bool)(this["InfiniteRings"]));
            }
            set {
                this["InfiniteRings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableVapeMode {
            get {
                return ((bool)(this["EnableVapeMode"]));
            }
            set {
                this["EnableVapeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting {
            get {
                return ((bool)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
